package com.qait.automation.getpageobjects;

public enum Action
{
    CLICK, FILL_INPUT, SELECT_DROPDOWN_OPTION, SELECT_RADIO, CHECK_CHECKBOX, UNCHECK_CHECKBOX,
    JAVASCRIPT_CLICK, SWITCH_FRAME,


    RELOAD_PAGE, SWITCH_WINDOW, SWITCH_DEFAULT, ACCEPT_ALERT, DISMISS_ALERT
}